name: metageneration
channels:
  - conda-forge
  - bioconda
dependencies:
  - insilicoseq
  - python=3.10
  - pip
  - pip:
      - pandas
      - biopython
      - python-sat
      - scipy
      - pysam
      - future
      - joblib
